// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Edge struct {
	Cursor string    `json:"cursor"`
	Node   *Receiver `json:"node"`
}

type NewReceiver struct {
	Identifier string `json:"identifier"`
	Name       string `json:"name"`
	Email      string `json:"email"`
	PixKeyType string `json:"pixKeyType"`
	PixKey     string `json:"pixKey"`
}

type PageInfo struct {
	StartCursor string `json:"startCursor"`
	EndCursor   string `json:"endCursor"`
	HasNextPage *bool  `json:"hasNextPage"`
}

type Pix struct {
	KeyType string `json:"keyType"`
	Key     string `json:"key"`
}

type Receiver struct {
	ID         string  `json:"id"`
	Identifier string  `json:"identifier"`
	Name       string  `json:"name"`
	Email      string  `json:"email"`
	Pix        *Pix    `json:"pix"`
	Bank       *string `json:"bank"`
	Agency     *string `json:"agency"`
	Account    *string `json:"account"`
	Status     *string `json:"status"`
}

type Receivers struct {
	Edges    []*Edge   `json:"edges"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type UpdateReceiver struct {
	ID         string  `json:"id"`
	Identifier *string `json:"identifier"`
	Name       *string `json:"name"`
	Email      *string `json:"email"`
	PixKeyType *string `json:"pixKeyType"`
	PixKey     *string `json:"pixKey"`
}
