// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import "github.com/teste-transfeera/internal/entity"

type NewReceiver struct {
	Identifier string  `json:"identifier"`
	Name       string  `json:"name"`
	Email      string  `json:"email"`
	PixKeyType string  `json:"pixKeyType"`
	PixKey     string  `json:"pixKey"`
	Bank       *string `json:"bank"`
	Agency     *string `json:"agency"`
	Account    *string `json:"account"`
}

type Pix struct {
	KeyType string `json:"keyType"`
	Key     string `json:"key"`
}

type Receiver struct {
	ID         string  `json:"id"`
	Identifier string  `json:"identifier"`
	Name       string  `json:"name"`
	Email      string  `json:"email"`
	Pix        *Pix    `json:"pix"`
	Bank       *string `json:"bank"`
	Agency     *string `json:"agency"`
	Account    *string `json:"account"`
	Status     *string `json:"status"`
}

func ToOutput(entity entity.Receiver) *Receiver {
	return &Receiver{
		ID:         entity.ID,
		Name:       entity.Name,
		Email:      entity.Email,
		Identifier: entity.Identifier,
		Pix: &Pix{
			KeyType: string(entity.Pix.KeyType),
			Key:     entity.Pix.Key,
		},
	}
}